name: Python CI

on:
  push:
    paths:
      - "python/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "python/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        cd python
        pytest

    - name: Run pytest with HTML report
      run: |
        cd python
        pytest --html=report.html

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: html-test-report
        path: python/report.html
